title: NangMan
description: Moonwalk test
theme: null

remote_theme: abhinavs/moonwalk

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag


# theme: minima
# theme: jekyll-theme-minimal
# theme:  jekyll-theme-cayman
# theme: jekyll-theme-slate

# DarkMode
# theme: jekyll-theme-midnight
# theme: jekyll-theme-chirpy

