title: My Jekyll Site
remote_theme: abhinavs/moonwalk


# theme: minima
# theme: jekyll-theme-minimal
# theme:  jekyll-theme-cayman
# theme: jekyll-theme-slate

# DarkMode
# theme: jekyll-theme-midnight
# theme: jekyll-theme-chirpy
# remote_theme: abhinavs/moonwalk
