title: Docs Dark
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

# 다크모드 토글 켜기
color_scheme: light dark
enable_dark_mode: true




# theme: minima
# theme: jekyll-theme-minimal
# theme:  jekyll-theme-cayman
# theme: jekyll-theme-slate

# DarkMode
# theme: jekyll-theme-midnight
# theme: jekyll-theme-chirpy

