title: My Jekyll Site


# Moonwalk remote theme 설정
remote_theme: abhinavs/moonwalk
plugins:
  - jekyll-remote-theme



# theme: minima
# theme: jekyll-theme-minimal
# theme:  jekyll-theme-cayman
# theme: jekyll-theme-slate

# DarkMode
# theme: jekyll-theme-midnight
# theme: jekyll-theme-chirpy
