title: Dark Blog
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-feed

# 다크 스킨 고정
minimal_mistakes_skin: dark




# theme: minima
# theme: jekyll-theme-minimal
# theme:  jekyll-theme-cayman
# theme: jekyll-theme-slate

# DarkMode
# theme: jekyll-theme-midnight
# theme: jekyll-theme-chirpy

