title: NangMan
description: Moonwalk test

remote_theme: abhinavs/moonwalk

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-feed

markdown: kramdown




# theme: minima
# theme: jekyll-theme-minimal
# theme:  jekyll-theme-cayman
# theme: jekyll-theme-slate

# DarkMode
# theme: jekyll-theme-midnight
# theme: jekyll-theme-chirpy

