title: My Dark Site
description: Simple dark theme
remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag





# theme: minima
# theme: jekyll-theme-minimal
# theme:  jekyll-theme-cayman
# theme: jekyll-theme-slate

# DarkMode
# theme: jekyll-theme-midnight
# theme: jekyll-theme-chirpy

